version: '3'

services:

  mariadb:
    image: mariadb:v1
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    networks:
      - inception
    #ports: ### ??
    #  - "3306:3306" ### ??
    volumes:
      - volume_mariadb:/var/lib/mysql
    restart: always

  wordpress:
    image: wordpress:v1
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - volume_wordpress:/var/www/html
    restart: always

  nginx:
    image: nginx:v1
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - volume_wordpress:/var/www/html
    restart: always
    # restart: unless-stopped # not allowed in subj

volumes:
  volume_wordpress:
    driver: local
    driver_opts:
      o: bind # bind mount, for path in host machine & outside docker volume, 
      type: none
      device: /home/${USER}/data/wordpress
  volume_mariadb:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb

networks:
  inception:
    driver: bridge
